{% set name = "pygis" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: eabfe67866b215b13c725a7ec57ec86a7e3d7cf5653c82fc5d3935f798509250

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - bokeh
    - datapane
    - geedim >=1.6.1
    - geemap >=0.22.1
    - geopandas
    - ipynb-py-convert
    - keplergl
    - leafmap >=0.21.3
    - localtileserver >=0.6.1
    - mapclassify >=2.4.0
    - netcdf4
    - osmnx
    - owslib
    - palettable
    - plotly
    - pydeck
    - python-mss
    - retry
    - rio-cogeo
    - rioxarray

    # - voila
    # - ipython >=7.34.0
    # - ipykernel >=6.15.1
    # - debugpy >=1.6.2
    # - ipygany
    # - ipyvtklink
    # - laspy
    # - panel
    # - pyntcloud
    # - pyvista

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/pygis
  summary: A Python package for installing optional dependencies for geemap and leafmap.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/giswqs/pygis

extra:
  recipe-maintainers:
    - giswqs
