{% set name = "pygis" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: b41854c0ac6069f0f3bf5762d9f7cd0e2a59096a02bb8d8cdb6a84553dfe6b54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - datapane
    - geemap >=0.13.8
    - geopandas
    - here-map-widget-for-jupyter
    - keplergl
    - leafmap >=0.9.3
    - ipygany
    - ipynb-py-convert
    - ipyvtklink
    - laspy
    - localtileserver >=0.5.8
    - netcdf4
    - osmnx
    - owslib
    - palettable
    - panel
    - plotly
    - pydeck
    - pyntcloud
    - python-mss
    - pyvista
    - rio-cogeo
    - rioxarray
    - voila

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/pygis
  summary: A Python package for installing optional dependencies for geemap and leafmap.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/giswqs/pygis

extra:
  recipe-maintainers:
    - giswqs
