{% set name = "pygis" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygis-{{ version }}.tar.gz
  sha256: 446401a80617f4491ebe7c86c5164fff47ca9704019051868d210c07a34d7ae3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - datapane
    - geedim >=1.2.0
    - geemap >=0.14.0
    - geopandas
    - here-map-widget-for-jupyter
    - ipynb-py-convert
    - keplergl
    - leafmap >=0.9.4
    - localtileserver >=0.5.8
    - mapclassify >=2.4.0
    - netcdf4
    - osmnx
    - owslib
    - palettable
    - plotly
    - pydeck
    - python-mss
    - rio-cogeo
    - rioxarray
    - voila
    # - ipygany
    # - ipyvtklink
    # - laspy
    # - panel
    # - pyntcloud
    # - pyvista

test:
  imports:
    - pygis
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/pygis
  summary: A Python package for installing optional dependencies for geemap and leafmap.
  description: A Python package for installing commonly used packages for geospatial analysis and data visualization with only one command. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pygis.gishub.org
  dev_url: https://github.com/giswqs/pygis

extra:
  recipe-maintainers:
    - giswqs
